name: Java Maven Build

on:
  push:
    branches: 
      - '**'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [ latest ]
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: maven

      - name: Show versions
        run: java -version && ./mvnw -version && gpg --version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Prepare headless run
        run: |
          echo "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500" >> ${{ github.workspace }}/.mvn/jvm.config

      - name: Build with Maven
        uses: coactions/setup-xvfb@v1
        with:
          run: ./mvnw clean package -U -B -ntp --file pom.xml -s settings.xml
        env:
          NO_DOCKER: ${{ runner.os != 'Linux' }}
